### ISSUE TITLE
403 forbidden on metrics

### ISSUE THREAD

**Issue by tzapu** [PegaSysEng/eth2signer#97] opened 2020-06-11 22:02 UTC
hello
when i try  to connect to metrics from another pod, i get 403 forbidden back.
i have started eth2signer with:
```
--http-listen-port=9000                                                                                                                                                                
--http-listen-host=0.0.0.0                                                                                                                                                                  --key-store-path=/data                                                                                                                                                                      --logging=ALL                                                                                                                                                                          
--metrics-enabled                                                                                                                                                                     
--metrics-port=9001                                                                                                                                                                          --metrics-host=0.0.0.0
```
and i get metrics if i get a shell in the container, install curl and use it. 
unfortunately, when i try to connect from another pod/container i get 403. prometheus also reports 403

cheers

**Comment by usmansaleem** [comment] 2020-06-15 00:47
Try using `--metrics-host`

**Comment by tzapu** [comment] 2020-06-15 13:36
for some reason i did not paste that... here are all the args
```
  - --http-listen-port={{ .Values.service.port }}
          - --http-listen-host=0.0.0.0
          - --key-store-path=/data
          - --logging=ALL
          - --metrics-enabled
          - --metrics-port={{ .Values.service.metricsPort }}
          - --metrics-host=0.0.0.0
```

**Comment by jframe** [comment] 2020-06-22 06:56
Found the cause of this issue. The metrics endpoint is configured with host allow list that defaults to localhost. So by default you can only access metrics on localhost.

So the fix is to allow configuration of the allow host list with another config option --metrics-allow-hostlist which is a comma separated list of hostnames to allow for metrics access, or * to accept any host defaulting to localhost, 127.0.01.

**Comment by tzapu** [comment] 2020-06-22 09:32
super cool, thanks, waiting for it to be merged :D

**Comment by jframe** [comment] 2020-06-23 04:47
Merged the fix with the new command line option --metricsHostAllowList into master. Also added a configurable value metricsHostAllowList in the helm chart.

**Comment by tzapu** [comment] 2020-06-23 07:56
i can confirm this now works properly 
![image](https://user-images.githubusercontent.com/2983312/85376313-33370680-b540-11ea-8d42-d3c99af7243f.png)

have you guys got some sample grafana dashboard perchance?
cheers

**Comment by jframe** [comment] 2020-06-23 23:08
Glad it's working now. No unfortunately we don't have a sample dashboard

**Comment by bgravenorst** [comment] 2020-07-06 23:39
This has been documented here:
https://docs.eth2signer.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#metrics-host-allowlist

**Closed** 2020-07-06 23:39 UTC
Labels: TeamGroot, bug
